apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankshield-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: bankshield
  source:
    repoURL: https://github.com/bankshield/bankshield-k8s
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
      include: "*.yaml"
    helm:
      valueFiles:
      - values.yaml
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: bankshield-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    managedNamespaceMetadata:
      labels:
        bankshield.io/managed-by: argocd
  revisionHistoryLimit: 5
  info:
  - name: Description
    value: BankShield开发环境
  - name: Owner
    value: devops-team@bankshield.com